export enum LoginState {
  LOGGED_IN = 'LOGGED_IN',
  LOGIN_IN_PROGRESS = 'LOGIN_IN_PROGRESS',
  LOGIN_FAILED = 'LOGIN_FAILED',
  LOGGED_OUT = 'LOGGED_OUT',
  LOGOUT_IN_PROGRESS = 'LOGOUT_IN_PROGRESS',
}
